package activity

const (
	BucketCreated                string = "BUCKET_CREATED"
	BucketDeleted                string = "BUCKET_DELETED"
	FileUploaded                 string = "FILE_UPLOADED"
	FileDownloaded               string = "FILE_DOWNLOADED"
	FileUpdated                  string = "FILE_UPDATED"
	FileDeleted                  string = "FILE_DELETED"
	FileExpired                  string = "FILE_EXPIRED"
	FileTrashed                  string = "FILE_TRASHED"
	FileRestored                 string = "FILE_RESTORED"
	FolderCreated                string = "FOLDER_CREATED"
	FolderUpdated                string = "FOLDER_UPDATED"
	FolderTrashed                string = "FOLDER_TRASHED"
	FolderRestored               string = "FOLDER_RESTORED"
	FolderDeleted                string = "FOLDER_DELETED"
	BucketMemberCreated          string = "BUCKET_MEMBER_CREATED"
	BucketMemberUpdated          string = "BUCKET_MEMBER_UPDATED"
	BucketMemberDeleted          string = "BUCKET_MEMBER_DELETED"
	UserLoggedIn                 string = "USER_LOGGED_IN"
	PasswordResetCodeVerified    string = "PASSWORD_RESET_CODE_VERIFIED"
	PasswordResetMFAVerified     string = "PASSWORD_RESET_MFA_VERIFIED"
	PasswordResetCompleted       string = "PASSWORD_RESET_COMPLETED"
	InviteAccepted               string = "INVITE_ACCEPTED"
	InviteChallengeAttemptFailed string = "INVITE_CHALLENGE_ATTEMPT_FAILED"
	InviteChallengeLocked        string = "INVITE_CHALLENGE_LOCKED"
	MFADeviceEnrolled            string = "MFA_DEVICE_ENROLLED"
	MFADeviceVerified            string = "MFA_DEVICE_VERIFIED"
	MFADeviceUpdated             string = "MFA_DEVICE_UPDATED"
	MFADeviceRemoved             string = "MFA_DEVICE_REMOVED"
)
