FROM fluent/fluentd:v1.17-1

USER root

# Install build dependencies and NATS client gem
RUN apk add --no-cache --update --virtual .build-deps \
    build-base \
    ruby-dev \
 && gem install nats-pure \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/*

USER fluent
