import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {SideMenu} from "@/components/side-menu";
import {ThemeProvider} from "@/components/theme-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{ children: React.ReactNode }>) {

    const buckets = [
        {
            id: 1,
            name: "Oomnitza bucket",
            files: [
                {
                    "id": 1,
                    "name": "stocks.xls"
                }
            ]
        },
        {
            id: 2,
            name: "HR bucket",
            files: [
                {
                    "id": 1,
                    "name": "contrat.pdf"
                }
            ]
        }
    ];

    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="w-full flex h-svh max-h-svh">
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <SideMenu buckets={buckets}/>
                {children}
            </ThemeProvider>
        </div>
        </body>
        </html>
    );
}
