import {
  ArchiveRestore,
  Clock,
  Eye,
  FileDiff,
  FileDown,
  FileMinus,
  FileUp,
  FolderMinus,
  FolderPen,
  FolderPlus,
  Link2,
  Link2Off,
  Share2,
  Smartphone,
  SmartphoneCharging,
  SmartphoneNfc,
  Trash2,
  UserMinus,
  UserPen,
  UserPlus,
} from "lucide-react";
import type { ActivityMessage } from "@/types/activity.ts";

export const messageMap = {
  BUCKET_CREATED: {
    messageKey: "activity.messages.bucket_created",
    icon: Share2,
    iconColor: "text-success",
    iconBg: "bg-success/10",
  },
  BUCKET_DELETED: {
    messageKey: "activity.messages.bucket_deleted",
    icon: Share2,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  FILE_UPLOADED: {
    messageKey: "activity.messages.file_uploaded",
    icon: FileUp,
    iconColor: "text-chart-1",
    iconBg: "bg-chart-1/10",
  },
  FILE_DOWNLOADED: {
    messageKey: "activity.messages.file_downloaded",
    icon: FileDown,
    iconColor: "text-chart-1",
    iconBg: "bg-chart-1/10",
  },
  FILE_UPDATED: {
    messageKey: "activity.messages.file_updated",
    icon: FileDiff,
    iconColor: "text-chart-1",
    iconBg: "bg-chart-1/10",
  },
  FILE_DELETED: {
    messageKey: "activity.messages.file_deleted",
    icon: FileMinus,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  FILE_EXPIRED: {
    messageKey: "activity.messages.file_expired",
    icon: Clock,
    iconColor: "text-warning",
    iconBg: "bg-warning/10",
  },
  FILE_TRASHED: {
    messageKey: "activity.messages.file_trashed",
    icon: Trash2,
    iconColor: "text-warning",
    iconBg: "bg-warning/10",
  },
  FILE_RESTORED: {
    messageKey: "activity.messages.file_restored",
    icon: ArchiveRestore,
    iconColor: "text-success",
    iconBg: "bg-success/10",
  },
  FOLDER_CREATED: {
    messageKey: "activity.messages.folder_created",
    icon: FolderPlus,
    iconColor: "text-success",
    iconBg: "bg-success/10",
  },
  FOLDER_UPDATED: {
    messageKey: "activity.messages.folder_updated",
    icon: FolderPen,
    iconColor: "text-chart-3",
    iconBg: "bg-chart-3/10",
  },
  FOLDER_TRASHED: {
    messageKey: "activity.messages.folder_trashed",
    icon: Trash2,
    iconColor: "text-warning",
    iconBg: "bg-warning/10",
  },
  FOLDER_RESTORED: {
    messageKey: "activity.messages.folder_restored",
    icon: ArchiveRestore,
    iconColor: "text-success",
    iconBg: "bg-success/10",
  },
  FOLDER_DELETED: {
    messageKey: "activity.messages.folder_deleted",
    icon: FolderMinus,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  BUCKET_MEMBER_CREATED: {
    messageKey: "activity.messages.bucket_member_created",
    icon: UserPlus,
    iconColor: "text-chart-4",
    iconBg: "bg-chart-4/10",
  },
  BUCKET_MEMBER_UPDATED: {
    messageKey: "activity.messages.bucket_member_updated",
    icon: UserPen,
    iconColor: "text-chart-4",
    iconBg: "bg-chart-4/10",
  },
  BUCKET_MEMBER_DELETED: {
    messageKey: "activity.messages.bucket_member_deleted",
    icon: UserMinus,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  MFA_DEVICE_ENROLLED: {
    messageKey: "activity.messages.mfa_device_enrolled",
    icon: SmartphoneCharging,
    iconColor: "text-chart-5",
    iconBg: "bg-chart-5/10",
  },
  MFA_DEVICE_VERIFIED: {
    messageKey: "activity.messages.mfa_device_verified",
    icon: SmartphoneNfc,
    iconColor: "text-success",
    iconBg: "bg-success/10",
  },
  MFA_DEVICE_UPDATED: {
    messageKey: "activity.messages.mfa_device_updated",
    icon: Smartphone,
    iconColor: "text-chart-5",
    iconBg: "bg-chart-5/10",
  },
  MFA_DEVICE_REMOVED: {
    messageKey: "activity.messages.mfa_device_removed",
    icon: Smartphone,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  SHARE_CREATED: {
    messageKey: "activity.messages.share_created",
    icon: Link2,
    iconColor: "text-success",
    iconBg: "bg-success/10",
  },
  SHARE_DELETED: {
    messageKey: "activity.messages.share_deleted",
    icon: Link2Off,
    iconColor: "text-destructive",
    iconBg: "bg-destructive/10",
  },
  SHARE_EXPIRED: {
    messageKey: "activity.messages.share_expired",
    icon: Clock,
    iconColor: "text-warning",
    iconBg: "bg-warning/10",
  },
  SHARE_MAX_VIEWS_REACHED: {
    messageKey: "activity.messages.share_max_views_reached",
    icon: Eye,
    iconColor: "text-warning",
    iconBg: "bg-warning/10",
  },
  SHARE_FILE_DOWNLOADED: {
    messageKey: "activity.messages.share_file_downloaded",
    icon: FileDown,
    iconColor: "text-chart-2",
    iconBg: "bg-chart-2/10",
  },
  SHARE_FILE_UPLOADED: {
    messageKey: "activity.messages.share_file_uploaded",
    icon: FileUp,
    iconColor: "text-chart-2",
    iconBg: "bg-chart-2/10",
  },
} satisfies Record<ActivityMessage, object>;
