-- +goose Up
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE buckets ALTER COLUMN id DROP DEFAULT;
ALTER TABLE memberships ALTER COLUMN id DROP DEFAULT;
ALTER TABLE folders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE files ALTER COLUMN id DROP DEFAULT;
ALTER TABLE invites ALTER COLUMN id DROP DEFAULT;
ALTER TABLE challenges ALTER COLUMN id DROP DEFAULT;
ALTER TABLE mfa_devices ALTER COLUMN id DROP DEFAULT;

-- +goose Down
ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE buckets ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE memberships ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE folders ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE files ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE invites ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE challenges ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE mfa_devices ALTER COLUMN id SET DEFAULT gen_random_uuid();
