/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthenticatedBucketsBucketIdRouteImport } from './routes/_authenticated/buckets/$bucketId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthCompleteIndexRouteImport } from './routes/auth/complete/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthMfaIndexRouteImport } from './routes/auth/mfa/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as InvitesIdIndexRouteImport } from './routes/invites/$id/index'
import { Route as SharesUuidIndexRouteImport } from './routes/shares/$uuid/index'
import { Route as AuthenticatedAdminActivityIndexRouteImport } from './routes/_authenticated/admin/activity/index'
import { Route as AuthenticatedAdminBucketsIndexRouteImport } from './routes/_authenticated/admin/buckets/index'
import { Route as AuthenticatedAdminDashboardIndexRouteImport } from './routes/_authenticated/admin/dashboard/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminSettingsDetailsRouteImport } from './routes/_authenticated/admin/settings/details'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedBucketsBucketIdIndexRouteImport } from './routes/_authenticated/buckets/$bucketId/index'
import { Route as AuthenticatedBucketsBucketIdActivityRouteImport } from './routes/_authenticated/buckets/$bucketId/activity'
import { Route as AuthenticatedBucketsBucketIdMembersRouteImport } from './routes/_authenticated/buckets/$bucketId/members'
import { Route as AuthenticatedBucketsBucketIdSettingsRouteImport } from './routes/_authenticated/buckets/$bucketId/settings'
import { Route as AuthenticatedBucketsBucketIdSharesRouteImport } from './routes/_authenticated/buckets/$bucketId/shares'
import { Route as AuthenticatedBucketsBucketIdTrashRouteImport } from './routes/_authenticated/buckets/$bucketId/trash'
import { Route as AuthenticatedSettingsPreferencesIndexRouteImport } from './routes/_authenticated/settings/preferences/index'
import { Route as AuthenticatedSettingsProfileIndexRouteImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthMfaSetupRequiredIndexRouteImport } from './routes/auth/mfa/setup-required/index'
import { Route as AuthProvidersProviderIndexRouteImport } from './routes/auth/providers/$provider/index'
import { Route as AuthResetPasswordIdIndexRouteImport } from './routes/auth/reset-password/$id/index'
import { Route as AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125RouteImport } from './routes/_authenticated/buckets/$bucketId/files/{-$folderId}'
import { Route as InvitesIdChallengesChallengeIdIndexRouteImport } from './routes/invites/$id/challenges/$challengeId/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBucketsBucketIdRoute =
  AuthenticatedBucketsBucketIdRouteImport.update({
    id: '/buckets/$bucketId',
    path: '/buckets/$bucketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthCompleteIndexRoute = AuthCompleteIndexRouteImport.update({
  id: '/auth/complete/',
  path: '/auth/complete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaIndexRoute = AuthMfaIndexRouteImport.update({
  id: '/auth/mfa/',
  path: '/auth/mfa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesIdIndexRoute = InvitesIdIndexRouteImport.update({
  id: '/invites/$id/',
  path: '/invites/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharesUuidIndexRoute = SharesUuidIndexRouteImport.update({
  id: '/shares/$uuid/',
  path: '/shares/$uuid/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminActivityIndexRoute =
  AuthenticatedAdminActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBucketsIndexRoute =
  AuthenticatedAdminBucketsIndexRouteImport.update({
    id: '/buckets/',
    path: '/buckets/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardIndexRoute =
  AuthenticatedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsDetailsRoute =
  AuthenticatedAdminSettingsDetailsRouteImport.update({
    id: '/settings/details',
    path: '/settings/details',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBucketsBucketIdIndexRoute =
  AuthenticatedBucketsBucketIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const AuthenticatedBucketsBucketIdActivityRoute =
  AuthenticatedBucketsBucketIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const AuthenticatedBucketsBucketIdMembersRoute =
  AuthenticatedBucketsBucketIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const AuthenticatedBucketsBucketIdSettingsRoute =
  AuthenticatedBucketsBucketIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const AuthenticatedBucketsBucketIdSharesRoute =
  AuthenticatedBucketsBucketIdSharesRouteImport.update({
    id: '/shares',
    path: '/shares',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const AuthenticatedBucketsBucketIdTrashRoute =
  AuthenticatedBucketsBucketIdTrashRouteImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const AuthenticatedSettingsPreferencesIndexRoute =
  AuthenticatedSettingsPreferencesIndexRouteImport.update({
    id: '/settings/preferences/',
    path: '/settings/preferences/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexRouteImport.update({
    id: '/settings/profile/',
    path: '/settings/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthMfaSetupRequiredIndexRoute =
  AuthMfaSetupRequiredIndexRouteImport.update({
    id: '/auth/mfa/setup-required/',
    path: '/auth/mfa/setup-required/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthProvidersProviderIndexRoute =
  AuthProvidersProviderIndexRouteImport.update({
    id: '/auth/providers/$provider/',
    path: '/auth/providers/$provider/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordIdIndexRoute =
  AuthResetPasswordIdIndexRouteImport.update({
    id: '/auth/reset-password/$id/',
    path: '/auth/reset-password/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route =
  AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125RouteImport.update({
    id: '/files/{-$folderId}',
    path: '/files/{-$folderId}',
    getParentRoute: () => AuthenticatedBucketsBucketIdRoute,
  } as any)
const InvitesIdChallengesChallengeIdIndexRoute =
  InvitesIdChallengesChallengeIdIndexRouteImport.update({
    id: '/invites/$id/challenges/$challengeId/',
    path: '/invites/$id/challenges/$challengeId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/buckets/$bucketId': typeof AuthenticatedBucketsBucketIdRouteWithChildren
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/auth/complete/': typeof AuthCompleteIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/mfa/': typeof AuthMfaIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/invites/$id/': typeof InvitesIdIndexRoute
  '/shares/$uuid/': typeof SharesUuidIndexRoute
  '/admin/settings/details': typeof AuthenticatedAdminSettingsDetailsRoute
  '/buckets/$bucketId/activity': typeof AuthenticatedBucketsBucketIdActivityRoute
  '/buckets/$bucketId/members': typeof AuthenticatedBucketsBucketIdMembersRoute
  '/buckets/$bucketId/settings': typeof AuthenticatedBucketsBucketIdSettingsRoute
  '/buckets/$bucketId/shares': typeof AuthenticatedBucketsBucketIdSharesRoute
  '/buckets/$bucketId/trash': typeof AuthenticatedBucketsBucketIdTrashRoute
  '/admin/activity/': typeof AuthenticatedAdminActivityIndexRoute
  '/admin/buckets/': typeof AuthenticatedAdminBucketsIndexRoute
  '/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/buckets/$bucketId/': typeof AuthenticatedBucketsBucketIdIndexRoute
  '/settings/preferences/': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/auth/mfa/setup-required/': typeof AuthMfaSetupRequiredIndexRoute
  '/auth/providers/$provider/': typeof AuthProvidersProviderIndexRoute
  '/auth/reset-password/$id/': typeof AuthResetPasswordIdIndexRoute
  '/buckets/$bucketId/files/{-$folderId}': typeof AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route
  '/invites/$id/challenges/$challengeId/': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/auth/complete': typeof AuthCompleteIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/mfa': typeof AuthMfaIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/invites/$id': typeof InvitesIdIndexRoute
  '/shares/$uuid': typeof SharesUuidIndexRoute
  '/admin/settings/details': typeof AuthenticatedAdminSettingsDetailsRoute
  '/buckets/$bucketId/activity': typeof AuthenticatedBucketsBucketIdActivityRoute
  '/buckets/$bucketId/members': typeof AuthenticatedBucketsBucketIdMembersRoute
  '/buckets/$bucketId/settings': typeof AuthenticatedBucketsBucketIdSettingsRoute
  '/buckets/$bucketId/shares': typeof AuthenticatedBucketsBucketIdSharesRoute
  '/buckets/$bucketId/trash': typeof AuthenticatedBucketsBucketIdTrashRoute
  '/admin/activity': typeof AuthenticatedAdminActivityIndexRoute
  '/admin/buckets': typeof AuthenticatedAdminBucketsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/buckets/$bucketId': typeof AuthenticatedBucketsBucketIdIndexRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/auth/mfa/setup-required': typeof AuthMfaSetupRequiredIndexRoute
  '/auth/providers/$provider': typeof AuthProvidersProviderIndexRoute
  '/auth/reset-password/$id': typeof AuthResetPasswordIdIndexRoute
  '/buckets/$bucketId/files/{-$folderId}': typeof AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route
  '/invites/$id/challenges/$challengeId': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/buckets/$bucketId': typeof AuthenticatedBucketsBucketIdRouteWithChildren
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/auth/complete/': typeof AuthCompleteIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/mfa/': typeof AuthMfaIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/invites/$id/': typeof InvitesIdIndexRoute
  '/shares/$uuid/': typeof SharesUuidIndexRoute
  '/_authenticated/admin/settings/details': typeof AuthenticatedAdminSettingsDetailsRoute
  '/_authenticated/buckets/$bucketId/activity': typeof AuthenticatedBucketsBucketIdActivityRoute
  '/_authenticated/buckets/$bucketId/members': typeof AuthenticatedBucketsBucketIdMembersRoute
  '/_authenticated/buckets/$bucketId/settings': typeof AuthenticatedBucketsBucketIdSettingsRoute
  '/_authenticated/buckets/$bucketId/shares': typeof AuthenticatedBucketsBucketIdSharesRoute
  '/_authenticated/buckets/$bucketId/trash': typeof AuthenticatedBucketsBucketIdTrashRoute
  '/_authenticated/admin/activity/': typeof AuthenticatedAdminActivityIndexRoute
  '/_authenticated/admin/buckets/': typeof AuthenticatedAdminBucketsIndexRoute
  '/_authenticated/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/buckets/$bucketId/': typeof AuthenticatedBucketsBucketIdIndexRoute
  '/_authenticated/settings/preferences/': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/auth/mfa/setup-required/': typeof AuthMfaSetupRequiredIndexRoute
  '/auth/providers/$provider/': typeof AuthProvidersProviderIndexRoute
  '/auth/reset-password/$id/': typeof AuthResetPasswordIdIndexRoute
  '/_authenticated/buckets/$bucketId/files/{-$folderId}': typeof AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route
  '/invites/$id/challenges/$challengeId/': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buckets/$bucketId'
    | '/activity/'
    | '/settings/'
    | '/auth/complete/'
    | '/auth/login/'
    | '/auth/mfa/'
    | '/auth/reset-password/'
    | '/invites/$id/'
    | '/shares/$uuid/'
    | '/admin/settings/details'
    | '/buckets/$bucketId/activity'
    | '/buckets/$bucketId/members'
    | '/buckets/$bucketId/settings'
    | '/buckets/$bucketId/shares'
    | '/buckets/$bucketId/trash'
    | '/admin/activity/'
    | '/admin/buckets/'
    | '/admin/dashboard/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/buckets/$bucketId/'
    | '/settings/preferences/'
    | '/settings/profile/'
    | '/auth/mfa/setup-required/'
    | '/auth/providers/$provider/'
    | '/auth/reset-password/$id/'
    | '/buckets/$bucketId/files/{-$folderId}'
    | '/invites/$id/challenges/$challengeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/'
    | '/activity'
    | '/settings'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/invites/$id'
    | '/shares/$uuid'
    | '/admin/settings/details'
    | '/buckets/$bucketId/activity'
    | '/buckets/$bucketId/members'
    | '/buckets/$bucketId/settings'
    | '/buckets/$bucketId/shares'
    | '/buckets/$bucketId/trash'
    | '/admin/activity'
    | '/admin/buckets'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/users'
    | '/buckets/$bucketId'
    | '/settings/preferences'
    | '/settings/profile'
    | '/auth/mfa/setup-required'
    | '/auth/providers/$provider'
    | '/auth/reset-password/$id'
    | '/buckets/$bucketId/files/{-$folderId}'
    | '/invites/$id/challenges/$challengeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/buckets/$bucketId'
    | '/_authenticated/activity/'
    | '/_authenticated/settings/'
    | '/auth/complete/'
    | '/auth/login/'
    | '/auth/mfa/'
    | '/auth/reset-password/'
    | '/invites/$id/'
    | '/shares/$uuid/'
    | '/_authenticated/admin/settings/details'
    | '/_authenticated/buckets/$bucketId/activity'
    | '/_authenticated/buckets/$bucketId/members'
    | '/_authenticated/buckets/$bucketId/settings'
    | '/_authenticated/buckets/$bucketId/shares'
    | '/_authenticated/buckets/$bucketId/trash'
    | '/_authenticated/admin/activity/'
    | '/_authenticated/admin/buckets/'
    | '/_authenticated/admin/dashboard/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/buckets/$bucketId/'
    | '/_authenticated/settings/preferences/'
    | '/_authenticated/settings/profile/'
    | '/auth/mfa/setup-required/'
    | '/auth/providers/$provider/'
    | '/auth/reset-password/$id/'
    | '/_authenticated/buckets/$bucketId/files/{-$folderId}'
    | '/invites/$id/challenges/$challengeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCompleteIndexRoute: typeof AuthCompleteIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthMfaIndexRoute: typeof AuthMfaIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  InvitesIdIndexRoute: typeof InvitesIdIndexRoute
  SharesUuidIndexRoute: typeof SharesUuidIndexRoute
  AuthMfaSetupRequiredIndexRoute: typeof AuthMfaSetupRequiredIndexRoute
  AuthProvidersProviderIndexRoute: typeof AuthProvidersProviderIndexRoute
  AuthResetPasswordIdIndexRoute: typeof AuthResetPasswordIdIndexRoute
  InvitesIdChallengesChallengeIdIndexRoute: typeof InvitesIdChallengesChallengeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buckets/$bucketId': {
      id: '/_authenticated/buckets/$bucketId'
      path: '/buckets/$bucketId'
      fullPath: '/buckets/$bucketId'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/complete/': {
      id: '/auth/complete/'
      path: '/auth/complete'
      fullPath: '/auth/complete/'
      preLoaderRoute: typeof AuthCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa/': {
      id: '/auth/mfa/'
      path: '/auth/mfa'
      fullPath: '/auth/mfa/'
      preLoaderRoute: typeof AuthMfaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$id/': {
      id: '/invites/$id/'
      path: '/invites/$id'
      fullPath: '/invites/$id/'
      preLoaderRoute: typeof InvitesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shares/$uuid/': {
      id: '/shares/$uuid/'
      path: '/shares/$uuid'
      fullPath: '/shares/$uuid/'
      preLoaderRoute: typeof SharesUuidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/activity/': {
      id: '/_authenticated/admin/activity/'
      path: '/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AuthenticatedAdminActivityIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buckets/': {
      id: '/_authenticated/admin/buckets/'
      path: '/buckets'
      fullPath: '/admin/buckets/'
      preLoaderRoute: typeof AuthenticatedAdminBucketsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard/': {
      id: '/_authenticated/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/details': {
      id: '/_authenticated/admin/settings/details'
      path: '/settings/details'
      fullPath: '/admin/settings/details'
      preLoaderRoute: typeof AuthenticatedAdminSettingsDetailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/buckets/$bucketId/': {
      id: '/_authenticated/buckets/$bucketId/'
      path: '/'
      fullPath: '/buckets/$bucketId/'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdIndexRouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/_authenticated/buckets/$bucketId/activity': {
      id: '/_authenticated/buckets/$bucketId/activity'
      path: '/activity'
      fullPath: '/buckets/$bucketId/activity'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdActivityRouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/_authenticated/buckets/$bucketId/members': {
      id: '/_authenticated/buckets/$bucketId/members'
      path: '/members'
      fullPath: '/buckets/$bucketId/members'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdMembersRouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/_authenticated/buckets/$bucketId/settings': {
      id: '/_authenticated/buckets/$bucketId/settings'
      path: '/settings'
      fullPath: '/buckets/$bucketId/settings'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdSettingsRouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/_authenticated/buckets/$bucketId/shares': {
      id: '/_authenticated/buckets/$bucketId/shares'
      path: '/shares'
      fullPath: '/buckets/$bucketId/shares'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdSharesRouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/_authenticated/buckets/$bucketId/trash': {
      id: '/_authenticated/buckets/$bucketId/trash'
      path: '/trash'
      fullPath: '/buckets/$bucketId/trash'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdTrashRouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/_authenticated/settings/preferences/': {
      id: '/_authenticated/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/settings/profile'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/mfa/setup-required/': {
      id: '/auth/mfa/setup-required/'
      path: '/auth/mfa/setup-required'
      fullPath: '/auth/mfa/setup-required/'
      preLoaderRoute: typeof AuthMfaSetupRequiredIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/providers/$provider/': {
      id: '/auth/providers/$provider/'
      path: '/auth/providers/$provider'
      fullPath: '/auth/providers/$provider/'
      preLoaderRoute: typeof AuthProvidersProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$id/': {
      id: '/auth/reset-password/$id/'
      path: '/auth/reset-password/$id'
      fullPath: '/auth/reset-password/$id/'
      preLoaderRoute: typeof AuthResetPasswordIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/buckets/$bucketId/files/{-$folderId}': {
      id: '/_authenticated/buckets/$bucketId/files/{-$folderId}'
      path: '/files/{-$folderId}'
      fullPath: '/buckets/$bucketId/files/{-$folderId}'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125RouteImport
      parentRoute: typeof AuthenticatedBucketsBucketIdRoute
    }
    '/invites/$id/challenges/$challengeId/': {
      id: '/invites/$id/challenges/$challengeId/'
      path: '/invites/$id/challenges/$challengeId'
      fullPath: '/invites/$id/challenges/$challengeId/'
      preLoaderRoute: typeof InvitesIdChallengesChallengeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSettingsDetailsRoute: typeof AuthenticatedAdminSettingsDetailsRoute
  AuthenticatedAdminActivityIndexRoute: typeof AuthenticatedAdminActivityIndexRoute
  AuthenticatedAdminBucketsIndexRoute: typeof AuthenticatedAdminBucketsIndexRoute
  AuthenticatedAdminDashboardIndexRoute: typeof AuthenticatedAdminDashboardIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSettingsDetailsRoute:
    AuthenticatedAdminSettingsDetailsRoute,
  AuthenticatedAdminActivityIndexRoute: AuthenticatedAdminActivityIndexRoute,
  AuthenticatedAdminBucketsIndexRoute: AuthenticatedAdminBucketsIndexRoute,
  AuthenticatedAdminDashboardIndexRoute: AuthenticatedAdminDashboardIndexRoute,
  AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBucketsBucketIdRouteChildren {
  AuthenticatedBucketsBucketIdActivityRoute: typeof AuthenticatedBucketsBucketIdActivityRoute
  AuthenticatedBucketsBucketIdMembersRoute: typeof AuthenticatedBucketsBucketIdMembersRoute
  AuthenticatedBucketsBucketIdSettingsRoute: typeof AuthenticatedBucketsBucketIdSettingsRoute
  AuthenticatedBucketsBucketIdSharesRoute: typeof AuthenticatedBucketsBucketIdSharesRoute
  AuthenticatedBucketsBucketIdTrashRoute: typeof AuthenticatedBucketsBucketIdTrashRoute
  AuthenticatedBucketsBucketIdIndexRoute: typeof AuthenticatedBucketsBucketIdIndexRoute
  AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route: typeof AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route
}

const AuthenticatedBucketsBucketIdRouteChildren: AuthenticatedBucketsBucketIdRouteChildren =
  {
    AuthenticatedBucketsBucketIdActivityRoute:
      AuthenticatedBucketsBucketIdActivityRoute,
    AuthenticatedBucketsBucketIdMembersRoute:
      AuthenticatedBucketsBucketIdMembersRoute,
    AuthenticatedBucketsBucketIdSettingsRoute:
      AuthenticatedBucketsBucketIdSettingsRoute,
    AuthenticatedBucketsBucketIdSharesRoute:
      AuthenticatedBucketsBucketIdSharesRoute,
    AuthenticatedBucketsBucketIdTrashRoute:
      AuthenticatedBucketsBucketIdTrashRoute,
    AuthenticatedBucketsBucketIdIndexRoute:
      AuthenticatedBucketsBucketIdIndexRoute,
    AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route:
      AuthenticatedBucketsBucketIdFilesChar123FolderIdChar125Route,
  }

const AuthenticatedBucketsBucketIdRouteWithChildren =
  AuthenticatedBucketsBucketIdRoute._addFileChildren(
    AuthenticatedBucketsBucketIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBucketsBucketIdRoute: typeof AuthenticatedBucketsBucketIdRouteWithChildren
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsPreferencesIndexRoute: typeof AuthenticatedSettingsPreferencesIndexRoute
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBucketsBucketIdRoute:
    AuthenticatedBucketsBucketIdRouteWithChildren,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsPreferencesIndexRoute:
    AuthenticatedSettingsPreferencesIndexRoute,
  AuthenticatedSettingsProfileIndexRoute:
    AuthenticatedSettingsProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCompleteIndexRoute: AuthCompleteIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthMfaIndexRoute: AuthMfaIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  InvitesIdIndexRoute: InvitesIdIndexRoute,
  SharesUuidIndexRoute: SharesUuidIndexRoute,
  AuthMfaSetupRequiredIndexRoute: AuthMfaSetupRequiredIndexRoute,
  AuthProvidersProviderIndexRoute: AuthProvidersProviderIndexRoute,
  AuthResetPasswordIdIndexRoute: AuthResetPasswordIdIndexRoute,
  InvitesIdChallengesChallengeIdIndexRoute:
    InvitesIdChallengesChallengeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
