/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as InvitesIdIndexRouteImport } from './routes/invites/$id/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthMfaIndexRouteImport } from './routes/auth/mfa/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthCompleteIndexRouteImport } from './routes/auth/complete/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthResetPasswordIdIndexRouteImport } from './routes/auth/reset-password/$id/index'
import { Route as AuthMfaSetupRequiredIndexRouteImport } from './routes/auth/mfa/setup-required/index'
import { Route as AuthenticatedSettingsProfileIndexRouteImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthenticatedSettingsPreferencesIndexRouteImport } from './routes/_authenticated/settings/preferences/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminDashboardIndexRouteImport } from './routes/_authenticated/admin/dashboard/index'
import { Route as AuthenticatedAdminBucketsIndexRouteImport } from './routes/_authenticated/admin/buckets/index'
import { Route as AuthenticatedAdminActivityIndexRouteImport } from './routes/_authenticated/admin/activity/index'
import { Route as AuthenticatedBucketsBucketIdChar123FolderIdChar125RouteImport } from './routes/_authenticated/buckets/$bucketId/{-$folderId}'
import { Route as InvitesIdChallengesChallengeIdIndexRouteImport } from './routes/invites/$id/challenges/$challengeId/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InvitesIdIndexRoute = InvitesIdIndexRouteImport.update({
  id: '/invites/$id/',
  path: '/invites/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaIndexRoute = AuthMfaIndexRouteImport.update({
  id: '/auth/mfa/',
  path: '/auth/mfa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteIndexRoute = AuthCompleteIndexRouteImport.update({
  id: '/auth/complete/',
  path: '/auth/complete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthResetPasswordIdIndexRoute =
  AuthResetPasswordIdIndexRouteImport.update({
    id: '/auth/reset-password/$id/',
    path: '/auth/reset-password/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthMfaSetupRequiredIndexRoute =
  AuthMfaSetupRequiredIndexRouteImport.update({
    id: '/auth/mfa/setup-required/',
    path: '/auth/mfa/setup-required/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexRouteImport.update({
    id: '/settings/profile/',
    path: '/settings/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPreferencesIndexRoute =
  AuthenticatedSettingsPreferencesIndexRouteImport.update({
    id: '/settings/preferences/',
    path: '/settings/preferences/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardIndexRoute =
  AuthenticatedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBucketsIndexRoute =
  AuthenticatedAdminBucketsIndexRouteImport.update({
    id: '/buckets/',
    path: '/buckets/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityIndexRoute =
  AuthenticatedAdminActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBucketsBucketIdChar123FolderIdChar125Route =
  AuthenticatedBucketsBucketIdChar123FolderIdChar125RouteImport.update({
    id: '/buckets/$bucketId/{-$folderId}',
    path: '/buckets/$bucketId/{-$folderId}',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const InvitesIdChallengesChallengeIdIndexRoute =
  InvitesIdChallengesChallengeIdIndexRouteImport.update({
    id: '/invites/$id/challenges/$challengeId/',
    path: '/invites/$id/challenges/$challengeId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/auth/complete/': typeof AuthCompleteIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/mfa/': typeof AuthMfaIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/invites/$id/': typeof InvitesIdIndexRoute
  '/buckets/$bucketId/{-$folderId}': typeof AuthenticatedBucketsBucketIdChar123FolderIdChar125Route
  '/admin/activity/': typeof AuthenticatedAdminActivityIndexRoute
  '/admin/buckets/': typeof AuthenticatedAdminBucketsIndexRoute
  '/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/settings/preferences/': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/auth/mfa/setup-required/': typeof AuthMfaSetupRequiredIndexRoute
  '/auth/reset-password/$id/': typeof AuthResetPasswordIdIndexRoute
  '/invites/$id/challenges/$challengeId/': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/auth/complete': typeof AuthCompleteIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/mfa': typeof AuthMfaIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/invites/$id': typeof InvitesIdIndexRoute
  '/buckets/$bucketId/{-$folderId}': typeof AuthenticatedBucketsBucketIdChar123FolderIdChar125Route
  '/admin/activity': typeof AuthenticatedAdminActivityIndexRoute
  '/admin/buckets': typeof AuthenticatedAdminBucketsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/auth/mfa/setup-required': typeof AuthMfaSetupRequiredIndexRoute
  '/auth/reset-password/$id': typeof AuthResetPasswordIdIndexRoute
  '/invites/$id/challenges/$challengeId': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/auth/complete/': typeof AuthCompleteIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/mfa/': typeof AuthMfaIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/invites/$id/': typeof InvitesIdIndexRoute
  '/_authenticated/buckets/$bucketId/{-$folderId}': typeof AuthenticatedBucketsBucketIdChar123FolderIdChar125Route
  '/_authenticated/admin/activity/': typeof AuthenticatedAdminActivityIndexRoute
  '/_authenticated/admin/buckets/': typeof AuthenticatedAdminBucketsIndexRoute
  '/_authenticated/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/settings/preferences/': typeof AuthenticatedSettingsPreferencesIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/auth/mfa/setup-required/': typeof AuthMfaSetupRequiredIndexRoute
  '/auth/reset-password/$id/': typeof AuthResetPasswordIdIndexRoute
  '/invites/$id/challenges/$challengeId/': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/activity/'
    | '/settings/'
    | '/auth/complete/'
    | '/auth/login/'
    | '/auth/mfa/'
    | '/auth/reset-password/'
    | '/invites/$id/'
    | '/buckets/$bucketId/{-$folderId}'
    | '/admin/activity/'
    | '/admin/buckets/'
    | '/admin/dashboard/'
    | '/admin/users/'
    | '/settings/preferences/'
    | '/settings/profile/'
    | '/auth/mfa/setup-required/'
    | '/auth/reset-password/$id/'
    | '/invites/$id/challenges/$challengeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/'
    | '/activity'
    | '/settings'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/invites/$id'
    | '/buckets/$bucketId/{-$folderId}'
    | '/admin/activity'
    | '/admin/buckets'
    | '/admin/dashboard'
    | '/admin/users'
    | '/settings/preferences'
    | '/settings/profile'
    | '/auth/mfa/setup-required'
    | '/auth/reset-password/$id'
    | '/invites/$id/challenges/$challengeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/activity/'
    | '/_authenticated/settings/'
    | '/auth/complete/'
    | '/auth/login/'
    | '/auth/mfa/'
    | '/auth/reset-password/'
    | '/invites/$id/'
    | '/_authenticated/buckets/$bucketId/{-$folderId}'
    | '/_authenticated/admin/activity/'
    | '/_authenticated/admin/buckets/'
    | '/_authenticated/admin/dashboard/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/settings/preferences/'
    | '/_authenticated/settings/profile/'
    | '/auth/mfa/setup-required/'
    | '/auth/reset-password/$id/'
    | '/invites/$id/challenges/$challengeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCompleteIndexRoute: typeof AuthCompleteIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthMfaIndexRoute: typeof AuthMfaIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  InvitesIdIndexRoute: typeof InvitesIdIndexRoute
  AuthMfaSetupRequiredIndexRoute: typeof AuthMfaSetupRequiredIndexRoute
  AuthResetPasswordIdIndexRoute: typeof AuthResetPasswordIdIndexRoute
  InvitesIdChallengesChallengeIdIndexRoute: typeof InvitesIdChallengesChallengeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invites/$id/': {
      id: '/invites/$id/'
      path: '/invites/$id'
      fullPath: '/invites/$id/'
      preLoaderRoute: typeof InvitesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa/': {
      id: '/auth/mfa/'
      path: '/auth/mfa'
      fullPath: '/auth/mfa/'
      preLoaderRoute: typeof AuthMfaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete/': {
      id: '/auth/complete/'
      path: '/auth/complete'
      fullPath: '/auth/complete/'
      preLoaderRoute: typeof AuthCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/reset-password/$id/': {
      id: '/auth/reset-password/$id/'
      path: '/auth/reset-password/$id'
      fullPath: '/auth/reset-password/$id/'
      preLoaderRoute: typeof AuthResetPasswordIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa/setup-required/': {
      id: '/auth/mfa/setup-required/'
      path: '/auth/mfa/setup-required'
      fullPath: '/auth/mfa/setup-required/'
      preLoaderRoute: typeof AuthMfaSetupRequiredIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/settings/profile'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/preferences/': {
      id: '/_authenticated/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard/': {
      id: '/_authenticated/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buckets/': {
      id: '/_authenticated/admin/buckets/'
      path: '/buckets'
      fullPath: '/admin/buckets/'
      preLoaderRoute: typeof AuthenticatedAdminBucketsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity/': {
      id: '/_authenticated/admin/activity/'
      path: '/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AuthenticatedAdminActivityIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/buckets/$bucketId/{-$folderId}': {
      id: '/_authenticated/buckets/$bucketId/{-$folderId}'
      path: '/buckets/$bucketId/{-$folderId}'
      fullPath: '/buckets/$bucketId/{-$folderId}'
      preLoaderRoute: typeof AuthenticatedBucketsBucketIdChar123FolderIdChar125RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invites/$id/challenges/$challengeId/': {
      id: '/invites/$id/challenges/$challengeId/'
      path: '/invites/$id/challenges/$challengeId'
      fullPath: '/invites/$id/challenges/$challengeId/'
      preLoaderRoute: typeof InvitesIdChallengesChallengeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityIndexRoute: typeof AuthenticatedAdminActivityIndexRoute
  AuthenticatedAdminBucketsIndexRoute: typeof AuthenticatedAdminBucketsIndexRoute
  AuthenticatedAdminDashboardIndexRoute: typeof AuthenticatedAdminDashboardIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityIndexRoute: AuthenticatedAdminActivityIndexRoute,
  AuthenticatedAdminBucketsIndexRoute: AuthenticatedAdminBucketsIndexRoute,
  AuthenticatedAdminDashboardIndexRoute: AuthenticatedAdminDashboardIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedBucketsBucketIdChar123FolderIdChar125Route: typeof AuthenticatedBucketsBucketIdChar123FolderIdChar125Route
  AuthenticatedSettingsPreferencesIndexRoute: typeof AuthenticatedSettingsPreferencesIndexRoute
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedBucketsBucketIdChar123FolderIdChar125Route:
    AuthenticatedBucketsBucketIdChar123FolderIdChar125Route,
  AuthenticatedSettingsPreferencesIndexRoute:
    AuthenticatedSettingsPreferencesIndexRoute,
  AuthenticatedSettingsProfileIndexRoute:
    AuthenticatedSettingsProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCompleteIndexRoute: AuthCompleteIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthMfaIndexRoute: AuthMfaIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  InvitesIdIndexRoute: InvitesIdIndexRoute,
  AuthMfaSetupRequiredIndexRoute: AuthMfaSetupRequiredIndexRoute,
  AuthResetPasswordIdIndexRoute: AuthResetPasswordIdIndexRoute,
  InvitesIdChallengesChallengeIdIndexRoute:
    InvitesIdChallengesChallengeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
