/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as SettingsProfileIndexRouteImport } from './routes/settings/profile/index'
import { Route as SettingsPreferencesIndexRouteImport } from './routes/settings/preferences/index'
import { Route as InvitesIdIndexRouteImport } from './routes/invites/$id/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthCompleteIndexRouteImport } from './routes/auth/complete/index'
import { Route as BucketsIdSplatRouteImport } from './routes/buckets/$id/$'
import { Route as AuthResetPasswordIdIndexRouteImport } from './routes/auth/reset-password/$id/index'
import { Route as InvitesIdChallengesChallengeIdIndexRouteImport } from './routes/invites/$id/challenges/$challengeId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileIndexRoute = SettingsProfileIndexRouteImport.update({
  id: '/settings/profile/',
  path: '/settings/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesIndexRoute =
  SettingsPreferencesIndexRouteImport.update({
    id: '/settings/preferences/',
    path: '/settings/preferences/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitesIdIndexRoute = InvitesIdIndexRouteImport.update({
  id: '/invites/$id/',
  path: '/invites/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteIndexRoute = AuthCompleteIndexRouteImport.update({
  id: '/auth/complete/',
  path: '/auth/complete/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIdSplatRoute = BucketsIdSplatRouteImport.update({
  id: '/buckets/$id/$',
  path: '/buckets/$id/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIdIndexRoute =
  AuthResetPasswordIdIndexRouteImport.update({
    id: '/auth/reset-password/$id/',
    path: '/auth/reset-password/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitesIdChallengesChallengeIdIndexRoute =
  InvitesIdChallengesChallengeIdIndexRouteImport.update({
    id: '/invites/$id/challenges/$challengeId/',
    path: '/invites/$id/challenges/$challengeId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/buckets/$id/$': typeof BucketsIdSplatRoute
  '/auth/complete': typeof AuthCompleteIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/invites/$id': typeof InvitesIdIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/settings/profile': typeof SettingsProfileIndexRoute
  '/auth/reset-password/$id': typeof AuthResetPasswordIdIndexRoute
  '/invites/$id/challenges/$challengeId': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/buckets/$id/$': typeof BucketsIdSplatRoute
  '/auth/complete': typeof AuthCompleteIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/invites/$id': typeof InvitesIdIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
  '/settings/profile': typeof SettingsProfileIndexRoute
  '/auth/reset-password/$id': typeof AuthResetPasswordIdIndexRoute
  '/invites/$id/challenges/$challengeId': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity/': typeof ActivityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/buckets/$id/$': typeof BucketsIdSplatRoute
  '/auth/complete/': typeof AuthCompleteIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/invites/$id/': typeof InvitesIdIndexRoute
  '/settings/preferences/': typeof SettingsPreferencesIndexRoute
  '/settings/profile/': typeof SettingsProfileIndexRoute
  '/auth/reset-password/$id/': typeof AuthResetPasswordIdIndexRoute
  '/invites/$id/challenges/$challengeId/': typeof InvitesIdChallengesChallengeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/settings'
    | '/buckets/$id/$'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/reset-password'
    | '/invites/$id'
    | '/settings/preferences'
    | '/settings/profile'
    | '/auth/reset-password/$id'
    | '/invites/$id/challenges/$challengeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/settings'
    | '/buckets/$id/$'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/reset-password'
    | '/invites/$id'
    | '/settings/preferences'
    | '/settings/profile'
    | '/auth/reset-password/$id'
    | '/invites/$id/challenges/$challengeId'
  id:
    | '__root__'
    | '/'
    | '/activity/'
    | '/settings/'
    | '/buckets/$id/$'
    | '/auth/complete/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/invites/$id/'
    | '/settings/preferences/'
    | '/settings/profile/'
    | '/auth/reset-password/$id/'
    | '/invites/$id/challenges/$challengeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  BucketsIdSplatRoute: typeof BucketsIdSplatRoute
  AuthCompleteIndexRoute: typeof AuthCompleteIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  InvitesIdIndexRoute: typeof InvitesIdIndexRoute
  SettingsPreferencesIndexRoute: typeof SettingsPreferencesIndexRoute
  SettingsProfileIndexRoute: typeof SettingsProfileIndexRoute
  AuthResetPasswordIdIndexRoute: typeof AuthResetPasswordIdIndexRoute
  InvitesIdChallengesChallengeIdIndexRoute: typeof InvitesIdChallengesChallengeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile/': {
      id: '/settings/profile/'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences/': {
      id: '/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$id/': {
      id: '/invites/$id/'
      path: '/invites/$id'
      fullPath: '/invites/$id'
      preLoaderRoute: typeof InvitesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete/': {
      id: '/auth/complete/'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/$id/$': {
      id: '/buckets/$id/$'
      path: '/buckets/$id/$'
      fullPath: '/buckets/$id/$'
      preLoaderRoute: typeof BucketsIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$id/': {
      id: '/auth/reset-password/$id/'
      path: '/auth/reset-password/$id'
      fullPath: '/auth/reset-password/$id'
      preLoaderRoute: typeof AuthResetPasswordIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$id/challenges/$challengeId/': {
      id: '/invites/$id/challenges/$challengeId/'
      path: '/invites/$id/challenges/$challengeId'
      fullPath: '/invites/$id/challenges/$challengeId'
      preLoaderRoute: typeof InvitesIdChallengesChallengeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  BucketsIdSplatRoute: BucketsIdSplatRoute,
  AuthCompleteIndexRoute: AuthCompleteIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  InvitesIdIndexRoute: InvitesIdIndexRoute,
  SettingsPreferencesIndexRoute: SettingsPreferencesIndexRoute,
  SettingsProfileIndexRoute: SettingsProfileIndexRoute,
  AuthResetPasswordIdIndexRoute: AuthResetPasswordIdIndexRoute,
  InvitesIdChallengesChallengeIdIndexRoute:
    InvitesIdChallengesChallengeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
